GET http://localhost:609/git/projects
githost: 10.133.2.104
token: k8JwARfaFB1Edxac4GCT
groupid: 53

###
GET http://localhost:609/git/projects/http_url_to_repo
githost: 10.133.2.104
token: k8JwARfaFB1Edxac4GCT
groupid: 53

###
GET http://localhost:609/git/projects/_links
githost: 10.133.2.104
token: k8JwARfaFB1Edxac4GCT
groupid: 53

###
GET http://localhost:609/git/projects_temp
githost: 10.133.2.104
token: k8JwARfaFB1Edxac4GCT
groupid: 53

###
