# 反编译文件位置:C:\\Users\\Administrator\\Desktop\\cinda_file\\7001_code_update_record\\20220323-product_20220314package\\multi_dir\\idea_decompile\\target_com
# svn代码class位置: C:\\Users\\Administrator\\IdeaProjects\\prod_merge\\src\\com

### this.增加
POST http://localhost:609/decompile/appendStr
Content-Type: application/json

{
  "check": true,
  "equalType": "CONTAIN",
  "codeType": "REMOVE_BLANK",
  "sourcesPath": "C:\\Users\\Administrator\\Desktop\\cinda_file\\7001_code_update_record\\20220323-product_20220314package\\multi_dir\\idea_decompile\\target_com",
  "targetsPath": "C:\\Users\\Administrator\\IdeaProjects\\prod_merge\\src\\com",
  "targetsType": "java",
  "appendRegStr": "this\\."
}

### 泛型增加
POST http://localhost:609/decompile/appendStr
Content-Type: application/json

{
  "check": true,
  "codeType": "KEEP_ORIGIN",
  "equalType": "EQUAL",
  "sourcesPath": "C:\\Users\\Administrator\\Desktop\\cinda_file\\code_update_record\\20220323-product_20220314package\\multi_dir\\idea_decompile\\itms_cinda\\WEB-INF\\classes\\com",
  "targetsPath": "C:\\Users\\Administrator\\IdeaProjects\\cindabase_v01.0.02_purpose_merge_production\\src\\com",
  "targetsType": "java",
  "appendRegStr": "<\\S+>"
}

